[package]
name = "advent-of-code-2022"
version = "0.1.0"
edition = "2021"
license = "MIT"
license-file = "LICENSE"
include = ["data/*.txt"]
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
